2-css
Druss25/dz-html_css pull request #2
Opened 2024-06-18 08:03 UTC by Druss25

2024-06-18 21:21 UTC, Levitinn requested changes

2024-06-18 21:21 UTC, Levitinn commented on 1-blog/index.html
> +        <div class="wrapper">
не враппер. секции, хедер, футер, должны занимать всю ширину страницы, а внутри каждого из них должен быть свой div class="container", который ограничивает ширину контента в секции

2024-06-18 21:21 UTC, Levitinn commented on 1-blog/index.html
> +            <header>
отступы у хедера (вертикальные) должны быть паддингом, так как ты задаешь отступ ВНУТРЬ самого хедера, а от отступ ОТ другого элемента

2024-06-18 21:21 UTC, Levitinn commented on 1-blog/index.html
> +                    <div class="hero__photo">
диву обертке нужно задать
```
max-width: 896px;
max-height: 594px;
width: 100%;
height: 100%;
```
а картинке внутри 
```
width: 100%;
height: 100%;
```

так ты задашь максимальные размеры для обертки, а картинка внутри будет всегда пытаться занять эти размеры. и при сужении экрана, картинка будет динамично уменьшаться. А в твоем случае, при экране с меньшей шириной чем картинка, она будет выходить за пределы экрана.

точно так же нужно поступать со всеми изображениями в верстке.

2024-06-23 11:08 UTC, Levitinn commented on 1-blog/index.html
> +        <div class="wrapper">
все еще не верно. сейчас у body задана макс ширина
<img width="1672" alt="image" src="https://github.com/Druss25/dz-html_css/assets/44999446/3479d1c2-f859-4b16-8caf-4e8e4580e84e">
а ширину контента нужно задавать с помощью div class="container"

2024-06-23 12:04 UTC, Druss25 commented on 1-blog/index.html
> +        <div class="wrapper">
Здесь у body задана ширина  макета - она равна 1440px.
А в секциях, хедер, футер, должны занимать всю ширину страницы - 1440px, а внутри каждого из них должен быть свой div class="container", который ограничивает ширину контента в секции 1080px

А вот этот код я вообще у себя не нашел:
 <form action="#">
                    <div>
                        <img src="./images/search.svg" alt="search" />
        <div class="wrapper">

2024-06-23 12:06 UTC, Druss25 commented on 1-blog/index.html
> +        <div class="wrapper">
Здесь у body задана ширина макета - она равна 1440px.
А в секциях, хедер, футер, должны занимать всю ширину страницы - 1440px, а внутри каждого из них должен быть свой div class="container", который ограничивает ширину контента в секции 1080px

А по первой части я вообще у себя не нашел этого кода.

2024-06-24 20:43 UTC, Levitinn approved these changes

2024-06-25 07:28 UTC, merged